export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Tips} from './Tips/Tips'
export {default as Footer} from './Footer/Footer'
export {default as Schedule} from './Schedule/Schedule'